Repository fledge-iot/fledge, pull requests merged in 2024-03, with the labels that each got.

#1297 FOGL-8452 unit tests added for alerts API and it's manager
  tests/unit/python/fledge/common/test_alert_manager.py
  tests/unit/python/fledge/services/core/api/test_alerts.py
Labels: unit tests

#1302 FOGL-8564 reference link fixes in OMF doc and duplicate label fixes
  docs/OMF.rst
  docs/scripts/plugin_and_service_documentation
Labels: documentation

#1305 FOGL-8525 Fix type for service in control pipeline source/destination
  docs/control.rst
Labels: documentation

#1301 FOGL-8557 Add storage plugin developers documentation
  docs/plugin_developers_guide/08_storage.rst
  docs/plugin_developers_guide/index.rst
Labels: documentation

#1307 FOGL-8521 Add configuration item type information
  docs/plugin_developers_guide/02_writing_plugins.rst
Labels: documentation

#1311 alert count fixes in both normal and safe mode; as used in Ping response
  python/fledge/services/core/api/common.py
Labels: bug

#1308 FOGL-8540 Add documentation for the update checker
  docs/images/alert.jpg
  docs/quick_start/index.rst
  docs/quick_start/update.rst
Labels: documentation

#1318 FOGL-8600 Update instructions in line with current version and file
  docs/quick_start/installing.rst
Labels: documentation
