Repository fledge-iot/fledge, pull requests merged in 2024-01, with the labels that each got.

#1266 FOGL-8356 Plugin update API fixes when schedule info does not exist for a service
  python/fledge/services/core/api/plugins/update.py
Labels: bug, API

#1268 FOGL-8415 Update plugin developers guide
  docs/plugin_developers_guide/02_writing_plugins.rst
Labels: documentation

#1249 Fogl 8284.initial
  VERSION
  python/fledge/services/core/api/scheduler.py
  python/fledge/services/core/api/service.py
  python/fledge/services/core/scheduler/scheduler.py
  python/fledge/services/core/server.py
  scripts/plugins/storage/postgres/downgrade/66.sql
  scripts/plugins/storage/postgres/init.sql
  scripts/plugins/storage/postgres/upgrade/67.sql
  scripts/plugins/storage/sqlite/downgrade/66.sql
  scripts/plugins/storage/sqlite/init.sql
  scripts/plugins/storage/sqlite/upgrade/67.sql
  scripts/plugins/storage/sqlitelb/downgrade/66.sql
  scripts/plugins/storage/sqlitelb/init.sql
  scripts/plugins/storage/sqlitelb/upgrade/67.sql
  scripts/services/dispatcher_c
  scripts/services/north_C
  scripts/services/notification_c
  scripts/services/south_c
  tests/unit/python/fledge/services/core/api/test_service.py
Labels: enhancement

#1273 FOGL-8439 Alerts feature
  VERSION
  python/fledge/common/alert_manager.py
  python/fledge/common/microservice_management_client/microservice_management_client.py
  python/fledge/services/common/microservice_management/routes.py
  python/fledge/services/core/api/alerts.py
  python/fledge/services/core/api/common.py
  python/fledge/services/core/routes.py
  python/fledge/services/core/server.py
  scripts/plugins/storage/postgres/downgrade/67.sql
  scripts/plugins/storage/postgres/init.sql
  scripts/plugins/storage/postgres/upgrade/68.sql
  scripts/plugins/storage/sqlite/downgrade/67.sql
  scripts/plugins/storage/sqlite/init.sql
  scripts/plugins/storage/sqlite/upgrade/68.sql
  scripts/plugins/storage/sqlitelb/downgrade/67.sql
  scripts/plugins/storage/sqlitelb/init.sql
  scripts/plugins/storage/sqlitelb/upgrade/68.sql
  tests/system/python/api/test_common.py
  tests/system/python/packages/test_available_and_install_api.py
  tests/unit/python/fledge/services/core/api/test_common_ping.py
Labels: feature

#1277 FOGL-8462 Control Pipeline filter order fixes
  python/fledge/services/core/api/control_service/pipeline.py
  tests/system/python/api/test_service.py
Labels: bug
