Repository fledge-iot/fledge, pull requests merged in 2024-08, with the labels that each got.

#1435 FOGL-8932 update password API fixes
  python/fledge/services/core/api/auth.py
  tests/system/python/api/test_endpoints_with_different_user_types.py
  tests/unit/python/fledge/services/core/api/test_auth_mandatory.py
Labels: bug

#1439 FOGL-8982 Add documentation on allow and deny lists
  docs/images/firewall.jpg
  docs/securing_fledge.rst
Labels: documentation

#1448 DOC fixes for FOGL-9029 changes
  docs/quick_start/north.rst
Labels: documentation

#1451 FOGL-8796 validate timestamp in API tests
  python/requirements-test.txt
  tests/system/python/api/test_alerts.py
  tests/system/python/api/test_audit.py
  tests/system/python/api/test_browser_assets.py
  tests/system/python/api/test_statistics.py
  tests/system/python/helpers/utils.py
Labels: API Tests

#1452 FOGL-8951 Response header fixes in backup API and also fixed empty timestamp issue for SQLite
  python/fledge/services/core/api/backup_restore.py
Labels: bug
