Repository fledge-iot/fledge, pull requests merged in 2025-06, with the labels that each got.

#1642 FOGL-9494 Additional exception handling related to passwords has been incorporated into the authentication user model API, accompanied by unit tests
  python/fledge/services/core/api/auth.py
  python/fledge/services/core/user_model.py
  tests/unit/python/fledge/services/core/api/test_auth_mandatory.py
  tests/unit/python/fledge/services/core/api/test_auth_optional.py
  tests/unit/python/fledge/services/core/test_user_model.py
Labels: improvements

#1646 FOGL-9851 Resolved broken links and suppressed warning logs
  docs/KERBEROS.rst
  docs/plugin_developers_guide/11_WSL2.rst
  docs/scripts/plugin_and_service_documentation
  docs/troubleshooting_pi-server_integration.rst
Labels: documentation

#1650 Corrections to the Docker system tests to eliminate user prompts
  tests/system/python/scripts/package/reset
Labels: System tests

#1655 FOGL-9905 Add documentation on the dashboard search option
  docs/images/DashboardSearch.jpg
  docs/quick_start/gui.rst
Labels: documentation

#1662 Documentation updates as we discontinue support for Ubuntu 18.04 LTS
  README.rst
  docs/building_fledge/04_installation.rst
  docs/building_fledge/building_fledge.rst
  docs/quick_start/installing.rst
  docs/quick_start/platforms.rst
Labels: documentation
